### ISSUE TITLE
Broadcast events aren't always included in $apply/$digest cycles

### ISSUE THREAD

**Issue by mikepugh** [mikepugh/AngularGeoFire#4]
The "on" function of a geoQuery object sets up a rootScope.$broadcast event, but this event doesn't always $digest properly.

The fix is to add a timeout() call around the broadcast.

``` javascript
self._timeout(function() {
          self._rootScope.$broadcast(broadcastName, key, location, distance);
});
```

**Comment by itkin** [comment]
i've a question dealing with `query`: why the need to broadcast to rootscope instead of using simple $apply or $safeApply in the Geofire.query callback, letting the dev do what they want then ? 

By doing so you divert from the geofire api, which is not really convenient, i don't really get your point ca you enlight us ?

many thanks !

**Comment by mikepugh** [comment]
@itkin The query method callbacks in GeoFire are events. Within an AngularJS app, I prefer to deal with these events using Angular's event system - which is $broadcast and $on handlers.
